### ISSUE TITLE
Don't think this package needs cython as a run dependency

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/hdbscan-feedstock#67]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Although the upstream repo has Cython as a dependency, I think it is not needed as a runtime dependency for this conda package, but just a build dependency (and maybe host, but probably not for that, either).

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by DManowitz** [comment]
@johnlees @lmcinnes What do you think about this?

**Comment by johnlees** [comment]
Sounds plausible, maybe if you make a PR removing it from run and host and see what the build system says?

**Comment by DManowitz** [comment]
> Sounds plausible, maybe if you make a PR removing it from run and host and see what the build system says?

I'll do that.  However, in looking at the recipe build section, I don't know why python, cython, and numpy are marked as needed only if `build_platform != target_platform`.  I can understand why `cross-python_{{ target_platform }}` is marked that way, but not the others.

Should I remove that restriction for python, cython, and numpy?

**Comment by johnlees** [comment]
I'm not sure sorry! Worth trying in your PR I'd say, or could also ask on the conda-forge gitter
